name: .NET Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # or your version

    - name: Restore dependencies
      run: dotnet restore ShopListApp.sln

    - name: Build
      run: dotnet build --no-restore ShopListApp.sln

    - name: Test
      run: dotnet test ShopListApp.sln
